jQuery(document).ready(function(){jQuery('.comment-reply-link').addClass('btn btn-sm btn-default')
jQuery('#submit, button[type=submit], html input[type=button], input[type=reset], input[type=submit]').addClass('btn btn-default')
jQuery('.widget_rss ul').addClass('media-list')
jQuery('.postform').addClass('form-control')
jQuery('table#wp-calendar').addClass('table table-striped')
jQuery('#submit, .tagcloud, button[type=submit], .comment-reply-link, .widget_rss ul, .postform, table#wp-calendar').show('fast')})
function SparklingIsMobile(){return((navigator.userAgent.match(/Android/i))||(navigator.userAgent.match(/webOS/i))||(navigator.userAgent.match(/iPhone/i))||(navigator.userAgent.match(/iPod/i))||(navigator.userAgent.match(/iPad/i))||(navigator.userAgent.match(/BlackBerry/)))}
function generateMobileMenu(){var menu=jQuery('#masthead .site-navigation-inner .navbar-collapse > ul.nav')
if(SparklingIsMobile()&&jQuery(window).width()>767){menu.addClass('sparkling-mobile-menu')}else{menu.removeClass('sparkling-mobile-menu')}}
jQuery(document).ready(function(){jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>100){jQuery('.scroll-to-top').fadeIn()}else{jQuery('.scroll-to-top').fadeOut()}})
jQuery('.scroll-to-top').click(function(){jQuery('html, body').animate({scrollTop:0},800)
return false})
jQuery('.sparkling-dropdown').click(function(evt){jQuery(this).parent().toggleClass('open')})
generateMobileMenu()
jQuery(window).resize(function(){generateMobileMenu()})})
jQuery(document).ready(function($){var $this,$adminbar,height
$this=$('.navbar-fixed-top')
$adminbar=$('#wpadminbar')
if(0!==$this.length){height=(0!==$adminbar.length)?Math.abs($this.height()-$adminbar.height()):$this.height()
$this.parent('header').css('margin-bottom',height)}})