(function(g){var window=this;var Xpa=function(a,b){return g.Vb(a,b)},W4=function(){},Ypa=function(a){if(a.yc&&"function"==typeof a.yc)return a.yc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Zpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.A)(a,b,void 0);else{if(a.Hd&&"function"==typeof a.Hd)var c=a.Hd();else if(a.yc&&"function"==typeof a.yc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Ypa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},X4=function(a){g.Um(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},Y4=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.Zm(a.l,b,c)},Z4=function(a){return(a=g.so(a))?new ActiveXObject(a):new XMLHttpRequest},$4=function(a,b){return b+" ["+a.ba+" "+a.D+" "+a.getStatus()+"]"},$pa=function(a){return"content-type"==a.toLowerCase()},a5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},aqa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},b5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},c5=function(a,b){if(a.g){a5(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},d5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;b5(a);c5(a)},e5=function(a){return a.g?a.g.readyState:0},f5=function(a){if(a.i&&"undefined"!=typeof g.bY)if(a.P[1]&&4==e5(a)&&2==a.getStatus())$4(a,"Local request error detected and ignored");
else if(a.C&&4==e5(a))g.Gg(a.Vv,0,a);else if(a.dispatchEvent("readystatechange"),4==e5(a)){$4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!bqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<e5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";b5(a)}}finally{c5(a)}}},g5=function(a){g.Sf.call(this);
this.headers=new g.Jm;this.N=a||null;this.i=!1;this.P=this.g=null;this.ba=this.D="";this.u=0;this.l="";this.o=this.W=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},h5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},cqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Ho.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Go(e)&&c.push(d):c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.A)(c,function(d){g.Ho.prototype.remove.call(this,d)},a)},i5=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},eqa=function(a,b){g.ab(a,b)||a.push(b)},j5=function(a){var b=0,c;
for(c in a)b++;return b},k5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},fqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a,b,c,d){var e=new g.Mm(null,void 0);
a&&g.Nm(e,a);b&&g.Om(e,b);c&&g.Pm(e,c);d&&(e.i=d);return e},l5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return fqa(a)},m5=function(){this.g=[];
this.i=[]},n5=function(a,b){g.Mp[a]=!0;
var c=g.Kp();c&&c.publish.apply(c,arguments);g.Mp[a]=!1},o5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Jm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",hqa(this,a.capabilities||""),iqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},hqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa(Xpa,jqa)).forEach(function(c){a.capabilities.add(c)})},iqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},p5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},q5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},r5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kqa=function(a){return new p5(a)},s5=function(a){return g.Ma(a)?(0,g.B)(a,kqa):[]},t5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},u5=function(a){return g.Ma(a)?"["+(0,g.B)(a,t5).join(",")+"]":"null"},v5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},w5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},x5=function(a,b){return g.Ya(a,function(c){return q5(c,b)})},y5=function(a){try{var b=(0,g.dt)(),c=(0,g.ct)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},mqa=function(){var a=(0,g.ct)();
a&&dqa(a,a.g.mf(!0))},z5=function(){var a=g.ft("yt-remote-connected-devices")||[];
g.rb(a);return a},nqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},A5=function(a){g.et("yt-remote-connected-devices",a,86400)},C5=function(){if(B5)return B5;
var a=g.ft("yt-remote-device-id");a||(a=v5(),g.et("yt-remote-device-id",a,31536E3));for(var b=z5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return B5=d},D5=function(){var a=z5(),b=C5();
g.ab(a,b);g.gt()&&g.tb(a,b);a=nqa(a);if(0==a.length)try{g.gs("remote_sid")}catch(c){}else try{g.fs("remote_sid",a.join(","),-1)}catch(c){}},E5=function(){return g.ft("yt-remote-session-browser-channel")},F5=function(){return g.ft("yt-remote-local-screens")||[]},G5=function(){g.et("yt-remote-lounge-token-expiration",!0,86400)},oqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(F5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&G5();
g.et("yt-remote-local-screens",a,31536E3)},pqa=function(a,b){g.et("yt-remote-session-browser-channel",a);
g.et("yt-remote-session-screen-id",b);var c=z5(),d=C5();g.ab(c,d)||c.push(d);A5(c);D5()},H5=function(a){a||(y5("yt-remote-session-screen-id"),y5("yt-remote-session-video-id"));
D5();a=z5();g.eb(a,C5());A5(a)},J5=function(){if(!I5){var a=g.Ro();
a&&(I5=new g.Bo(a))}return I5?!!I5.get("yt-remote-use-staging-server"):!1},K5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},L5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},N5=function(a){a.length?M5(a.shift(),function(){N5(a)}):O5()},qqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},M5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},O5=function(){var a=L5();
a&&a(!1,"No cast extension found")},P5=function(){if(rqa){var a=2,b=L5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;M5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",O5,c)}},sqa=function(){P5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);N5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},Q5=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Uc=b;this.u=(0,g.x)(this.eD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},R5=function(){},S5=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.$m(this);this.i=new g.Fg;this.i.setInterval(250)},U5=function(a,b,c){a.Xh=1;
a.Xf=X4(b.clone());a.sh=c;a.u=!0;T5(a,null)},V5=function(a,b,c,d,e){a.Xh=1;
a.Xf=X4(b.clone());a.sh=null;a.u=c;e&&(a.Pz=!1);T5(a,d)},T5=function(a,b){a.Fi=(0,g.H)();
W5(a);a.Eg=a.Xf.clone();Y4(a.Eg,"t",a.A);a.fl=0;a.sc=a.g.np(a.g.Tk()?b:null);0<a.Tp&&(a.Gn=new g.zl((0,g.x)(a.WA,a,a.sc),a.Tp));a.aa.ca(a.sc,"readystatechange",a.TL);var c=a.ah?g.cc(a.ah):{};a.sh?(a.no="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Eg,a.no,a.sh,c)):(a.no="GET",a.Pz&&!g.Od&&(c.Connection="close"),a.sc.send(a.Eg,a.no,null,c));a.g.te(1)},c6=function(a,b,c){for(var d=!0;!a.Qg&&a.fl<c.length;){var e=tqa(a,c);
if(e==X5){4==b&&(a.pg=4,Y5(15),d=!1);break}else if(e==Z5){a.pg=4;Y5(16);d=!1;break}else $5(a,e)}4==b&&0==c.length&&(a.pg=1,Y5(17),d=!1);a.xe=a.xe&&d;d||(a6(a),b6(a))},tqa=function(a,b){var c=a.fl,d=b.indexOf("\n",c);
if(-1==d)return X5;c=Number(b.substring(c,d));if(isNaN(c))return Z5;d+=1;if(d+c>b.length)return X5;var e=b.substr(d,c);a.fl=d+c;return e},f6=function(a,b){a.Fi=(0,g.H)();
W5(a);var c=b?window.location.hostname:"";a.Eg=a.Xf.clone();g.Um(a.Eg,"DOMAIN",c);g.Um(a.Eg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){a6(a);a.pg=7;Y5(22);b6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in d6)k=d6[l];else if(l in e6)k=d6[l]=e6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
d6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Nc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.kL,a);a.Be.parentWindow.d=(0,g.x)(a.Ty,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.Ty,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Dc(a.Eg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},W5=function(a){a.Ws=(0,g.H)()+a.o;
g6(a,a.o)},g6=function(a,b){if(null!=a.Yi)throw Error("WatchDog timer not null");
a.Yi=h6((0,g.x)(a.uL,a),b)},i6=function(a){a.Yi&&(g.v.clearTimeout(a.Yi),a.Yi=null)},b6=function(a){a.g.Tv()||a.Qg||a.g.tn(a)},a6=function(a){i6(a);
g.qf(a.Gn);a.Gn=null;a.i.stop();g.bn(a.aa);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},$5=function(a,b){try{a.g.Ny(a,b),a.g.te(4)}catch(c){}},k6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;j6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){k6(a,b,c,d,f)},f)})}},j6=function(a,b,c){var d=new Image;
d.onload=function(){try{l6(d),c(!0)}catch(e){}};
d.onerror=function(){try{l6(d),c(!1)}catch(e){}};
d.onabort=function(){try{l6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{l6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
k5(d,a)},l6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},m6=function(a){this.g=a;
this.i=new R5},o6=function(a){var b=n6(a.g,a.jj,"/mail/images/cleardot.gif");
X4(b);k6(b.toString(),5E3,(0,g.x)(a.lC,a),3,2E3);a.te(1)},q6=function(a){var b=a.g.F;
if(null!=b)Y5(5),b?(Y5(11),p6(a.g,a,!1)):(Y5(12),p6(a.g,a,!0));else if(a.Dd=new S5(a,void 0,void 0,void 0),a.Dd.ah=a.Rp,b=a.g,b=n6(b,b.Tk()?a.Sj:null,a.Sp),Y5(5),!g.Md||g.pd(10))Y4(b,"TYPE","xmlhttp"),V5(a.Dd,b,!1,a.Sj,!1);else{Y4(b,"TYPE","html");var c=a.Dd;a=!!a.Sj;c.Xh=3;c.Xf=X4(b.clone());f6(c,a)}},r6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new R5;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},uqa=function(a,b){this.g=a;
this.map=b;this.context=null},s6=function(a){g.sf.call(this,"statevent",a)},t6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},u6=function(a){g.sf.call(this,"serverreachability",a)},y6=function(a){v6(a);
if(3==a.g){var b=a.Bk++,c=a.gm.clone();g.Um(c,"SID",a.l);g.Um(c,"RID",b);g.Um(c,"TYPE","terminate");w6(a,c);b=new S5(a,a.l,b,void 0);b.Xh=2;b.Xf=X4(c.clone());k5(new Image,b.Xf.toString());b.Fi=(0,g.H)();W5(b)}x6(a)},A6=function(a){a.DC(1,0);
a.gm=n6(a,null,a.Qp);z6(a)},v6=function(a){a.fg&&(a.fg.abort(),a.fg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.qf&&(g.v.clearTimeout(a.qf),a.qf=null);B6(a);a.zd&&(a.zd.cancel(),a.zd=null);a.lg&&(g.v.clearTimeout(a.lg),a.lg=null)},C6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new uqa(a.zH++,b));2!=a.g&&3!=a.g||z6(a)},z6=function(a){a.zd||a.lg||(a.lg=h6((0,g.x)(a.Sy,a),0),a.Rh=0)},F6=function(a,b){if(1==a.g){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new S5(a,"",c,void 0);d.ah=null;var e=D6(a),f=a.gm.clone();g.Um(f,"RID",c);g.Um(f,"CVER","1");w6(a,f);U5(d,f,e);a.zd=d;a.g=2}}else 3==a.g&&(b?E6(a,b):0==a.i.length||a.zd||E6(a))},E6=function(a,b){if(b)if(6<a.Rg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Bk-1;var d=D6(a)}else c=b.C,d=b.sh;else c=a.Bk++,d=D6(a);var e=a.gm.clone();g.Um(e,"SID",a.l);g.Um(e,"RID",c);g.Um(e,"AID",a.ki);w6(a,e);c=new S5(a,a.l,c,a.Rh+1);c.ah=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.zd=c;U5(c,e,d)},w6=function(a,b){if(a.Rc){var c=a.Rc.xv();
c&&g.Lb(c,function(d,e){g.Um(b,e,d)})}},D6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Rg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Rg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},G6=function(a){a.Sb||a.qf||(a.C=1,a.qf=h6((0,g.x)(a.Ry,a),0),a.Jh=0)},I6=function(a){if(a.Sb||a.qf||3<=a.Jh)return!1;
a.C++;a.qf=h6((0,g.x)(a.Ry,a),H6(a,a.Jh));a.Jh++;return!0},p6=function(a,b,c){a.ko=c;
a.Je=b.Af;a.A||A6(a)},B6=function(a){null!=a.Vg&&(g.v.clearTimeout(a.Vg),a.Vg=null)},H6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K6=function(a,b){if(2==b||9==b){var c=null;
a.Rc&&(c=null);var d=(0,g.x)(a.yM,a);c||(c=new g.Mm("//www.google.com/images/cleardot.gif"),X4(c));j6(c.toString(),1E4,d)}else Y5(2);J6(a,b)},J6=function(a,b){a.g=0;
a.Rc&&a.Rc.zu(b);x6(a);v6(a)},x6=function(a){a.g=0;
a.Je=-1;if(a.Rc)if(0==a.o.length&&0==a.i.length)a.Rc.bp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Rc.bp(b)}},n6=function(a,b,c){var d=g.Vm(c);
if(""!=d.g)b&&g.Om(d,b+"."+d.g),g.Pm(d,d.u);else{var e=window.location;d=gqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.wj&&g.Lb(a.wj,function(f,k){g.Um(d,k,f)});
g.Um(d,"VER",a.Rg);w6(a,d);return d},h6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},Y5=function(a){L6.dispatchEvent(new s6(L6,a))},M6=function(){},vqa=function(a,b){this.action=a;
this.params=b||{}},N6=function(a,b){g.D.call(this);
this.g=new g.M(this.cL,0,this);g.G(this,this.g);this.Uc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},O6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Ao;this.i=new N6(this.cM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},wqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ko,sessionId:a.g.l,arrayId:a.g.ki}},P6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&F6(a.g),y6(a.g));a.D=0},Q6=function(a){return!!a.g&&3==a.g.g},xqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},R6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},S6=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},T6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),ie:g.Sa(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Eq(b,a)},yqa=function(){var a=U6;
V6();W6.push(a);X6(W6)},Y6=function(a,b){V6();
var c=W6,d=zqa(a,String(b));0==c.length?Aqa(d):(X6(c),(0,g.A)(c,function(e){e(d)}))},V6=function(){W6||(W6=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",W6,void 0))},Aqa=function(a){var b=(Z6+1)%50;
Z6=b;$6[b]=a;a7||(a7=49==b)},X6=function(a){var b=$6;
if(b[0]){var c=Z6,d=a7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(f){f(e)})}while(d!=c);
$6=Array(50);Z6=-1;a7=!1}},zqa=function(a,b){var c=((0,g.H)()-Bqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},b7=function(a){g.P.call(this);
this.C=a;this.g=[]},c7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!w5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=c7(a,b[d])||c;return c},Dqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},d7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},f7=function(a){b7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;e7(this);this.info("Initializing with "+u5(this.g))},g7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=S6(a.l,"/pairing/get_lounge_token_batch");
T6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.oD,a),(0,g.x)(a.nD,a))}},e7=function(a){var b=s5(F5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Cqa(a,b)},h7=function(a,b){oqa((0,g.B)(a.g,r5));
b&&G5()},j7=function(a,b){g.P.call(this);
this.A=b;var c=g.ft("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;i7("Initialized with "+g.Kg(this.g))},k7=function(a,b,c){var d=S6(a.u,"/pairing/get_screen_availability");
T6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},l7=function(a,b){a:if(j5(b)!=j5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(i7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.M("screenChange"));Eqa(a)},m7=function(a){isNaN(a.l)||g.Jp(a.l);
a.l=g.Hp((0,g.x)(a.Wr,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},i7=function(a){Y6("OnlineScreenService",a)},n7=function(a){var b={};
(0,g.A)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Eqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.et("yt-remote-online-screen-ids",a.join(","),60):y5("yt-remote-online-screen-ids")},o7=function(a){b7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Fqa(this)},q7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Jd();if(k=(c?x5(k,c):null)||x5(k,b)){k.uuid=b;var l=p7(a,k);k7(a.i,l,function(m){e(m?l:null)})}else c?Gqa(a,c,(0,g.x)(function(m){var n=p7(this,new p5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));k7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},r7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Gqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Eq(S6(a.A,"/pairing/get_lounge_token_batch"),e)},s7=function(a){a.g=a.l.Jd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+u5(a.g))},Fqa=function(a){t7(a);
a.l=new f7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.wD,a));s7(a);a.o=s5(g.ft("yt-remote-automatic-screen-cache")||[]);t7(a);a.info("Initializing automatic screens: "+u5(a.o));a.i=new j7(a.A,(0,g.x)(a.Jd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.M("onlineScreenChange")},a))},p7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=x5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.et("yt-remote-automatic-screen-cache",(0,g.B)(a.o,r5)));t7(a);a.u[b.uuid]=b.id;g.et("yt-remote-device-id-map",a.u,31536E3);return b},t7=function(a){a.u=g.ft("yt-remote-device-id-map")||{}},u7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},v7=function(a,b){Y6(a.P,b)},x7=function(a,b){u7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.dN,this);this.u=(0,g.x)(this.FL,this);this.o=g.Hp((0,g.x)(function(){w7(this,null)},this),12E4)},Hqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){v7(this,"Failed to send message: getMdxSessionStatus.")},a)):v7(a,"Sending yt message without session: "+g.Kg(b))},w7=function(a,b){g.Jp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.vn,a),d=(0,g.x)(a.Md,a);a.Nv(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},y7=function(a,b,c){u7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.gN,this);this.g=g.Ja},z7=function(a){a.g=a.F.bB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.vn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Md(b)},a))},A7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}J5()&&(b.env_useStageMdx=1);return g.ah(b)},B7=function(a,b){u7.call(this,a,b,"ManualSession");
this.g=g.Hp((0,g.x)(this.mi,this,null),150)},C7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.lK,this)},D7=function(a,b){return b?g.Ya(a.l,function(c){return q5(b,c.label)},a):null},E7=function(a){Y6("Controller",a)},U6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.u||!!a.l.length||!!a.g},G7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Qy,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.M("yt-remote-cast2-session-change",null))},H7=function(a){var b=a.i.aB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&q5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=D7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lqa=function(a,b,c,d,e,f,k){Iqa()?Jqa(b,e,f,k)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?K7(a,c):(window.__onGCastApiAvailable=function(l,m){l?K7(a,c):(L7("Failed to load cast API: "+m),M7(!1),J7(!1),y5("yt-remote-cast-available"),y5("yt-remote-cast-receiver"),N7(),c(!1))},d?g.Up("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?sqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?O5():(P5(),N5(Kqa.map(qqa))))):I7("Cannot initialize because not running Chrome")},N7=function(){I7("dispose");
var a=O7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);P7(!1);g.Pp(Q7);Q7.length=0},R7=function(){return!!g.ft("yt-remote-cast-installed")},S7=function(){var a=g.ft("yt-remote-cast-receiver");
return a?a.friendlyName:null},T7=function(){I7("clearCurrentReceiver");
y5("yt-remote-cast-receiver")},U7=function(){return R7()?O7()?O7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},W7=function(){R7()?O7()?V7()?(I7("Requesting cast selector."),O7().requestSession()):(I7("Wait for cast API to be ready to request the session."),Q7.push(g.Op("yt-remote-cast2-api-ready",W7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},X7=function(a,
b){V7()?O7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},Iqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Nw||a},Mqa=function(a,b){O7().init(a,b)},Jqa=function(a,b,c,d){var e=!1;
O7()||(a=new C7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.et("yt-remote-cast-available",f);n5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f);n5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+t5(f));
f||y5("yt-remote-cast-receiver");n5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},O7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},K7=function(a,b){M7(!0);
J7(!1);Mqa(a,function(c){c?(P7(!0),g.Rp("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),y5("yt-remote-cast-available"),y5("yt-remote-cast-receiver"),N7());b(c)})},I7=function(a){Y6("cloudview",a)},L7=function(a){Y6("cloudview",a)},M7=function(a){I7("setCastInstalled_ "+a);
g.et("yt-remote-cast-installed",a)},V7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},P7=function(a){I7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},Y7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ke=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},Z7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},$7=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},a8=function(a,b){a.C=b;
a.A=(0,g.H)()},b8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},c8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&Z7(a)},d8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},g8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new m5;this.l=this.i=null;this.F=(0,g.x)(this.iI,this);this.C=(0,g.x)(this.Ek,this);this.D=(0,g.x)(this.hI,this);this.H=(0,g.x)(this.vI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Zs,this),e8(this))):c=3;0!=c&&(b?this.Zs(c):g.Hp((0,g.x)(function(){this.Zs(c)},this),0));
var d=U7();d&&f8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},h8=function(a){return new Y7(a.o.getPlayerContextData())},e8=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.iK,b),this))},a)},i8=function(a){(0,g.A)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},j8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},l8=function(a,b,c){var d=h8(a);
a8(d,c);-1E3!=d.playerState&&(d.playerState=b);k8(a,d)},m8=function(a,b,c){a.o.sendMessage(b,c)},k8=function(a,b){i8(a);
a.o.setPlayerContextData(d8(b));e8(a)},f8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ek(null));
a.l=b;a.l&&(Y6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ek(a.l.media[0]))},n8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=h8(a);b.contentId!=d.videoId&&Y6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;a8(d,a.i.getEstimatedTime());k8(a,d)}else Y6("CP","No cast media video. Ignoring state update.")},o8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),m8(this,b,c))},a)},p8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Ma=this.g=null;this.O=a;this.P.push(g.Mr(window,"beforeunload",(0,g.x)(this.hD,this)));this.i=[];this.Ma=new Y7;this.N=b.id;this.g=Nqa(this,c);this.g.subscribe("handlerOpened",this.mI,this);this.g.subscribe("handlerClosed",this.jI,this);this.g.subscribe("handlerError",this.kI,this);this.g.subscribe("handlerMessage",this.lI,this);xqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ma.videoId;
g.gt()&&g.et("yt-remote-session-video-id",d)},this)},q8=function(a){Y6("conn",a)},Nqa=function(a,b){return new O6(S6(a.O,"/bc"),b)},r8=function(a,b){a.M("proxyStateChange",b)},Oqa=function(a){a.u=g.Hp((0,g.x)(function(){q8("Connecting timeout");
this.Nh(1)},a),2E4)},s8=function(a){g.Jp(a.u);
a.u=NaN},t8=function(a){g.Jp(a.H);
a.H=NaN},Pqa=function(a){u8(a);
a.F=g.Hp((0,g.x)(function(){v8(this,"getNowPlaying")},a),2E4)},u8=function(a){g.Jp(a.F);
a.F=NaN},x8=function(a,b){b&&(s8(a),t8(a));
b==(Q6(a.g)&&isNaN(a.u))?b&&(r8(a,1),v8(a,"getSubtitlesTrack")):b?(a.Kv()&&a.Ma.reset(),r8(a,1),v8(a,"getNowPlaying"),w8(a)):a.Nh(1)},Qqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ma.videoId&&(g.Yb(b.params)?a.Ma.g=null:a.Ma.g=b.params,a.M("remotePlayerChange"))},y8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ma.listId=b.params.listId||a.Ma.listId;c8(a.Ma,c,d);a.M("remoteQueueChange")},Rqa=function(a,b){b.params=b.params||{};
y8(a,b);z8(a,b);a.M("autoplayDismissed")},z8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
a8(a.Ma,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ma.playerState&&(c=-1E3);a.Ma.playerState=c;c=Number(b.params.loadedTime);a.Ma.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Ma.D=isNaN(c)?0:c;c=a.Ma;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Ma;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Ma.playerState?Pqa(a):u8(a);a.M("remotePlayerChange")},Sqa=function(a,b){if(-1E3!=
a.Ma.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ma.playerState=c;c=parseInt(b.params.currentTime,10);a8(a.Ma,isNaN(c)?0:c);a.M("remotePlayerChange")}},Tqa=function(a,b){var c="true"==b.params.muted;
a.Ma.volume=parseInt(b.params.volume,10);a.Ma.muted=c;a.M("remotePlayerChange")},Uqa=function(a,b){a.A=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},Vqa=function(a,b){var c="true"==b.params.hasNext;
a.Ma.Ke="true"==b.params.hasPrevious;a.Ma.hasNext=c;a.M("previousNextChange")},w8=function(a){g.Jp(a.D);
a.D=g.Hp((0,g.x)(a.Nh,a,1),864E5)},v8=function(a,b,c){c?q8("Sending: action="+b+", params="+g.Kg(c)):q8("Sending: action="+b);
a.g.sendMessage(b,c)},A8=function(a){b7.call(this,"ScreenServiceProxy");
this.Tc=a;this.i=[];this.i.push(this.Tc.$_s("screenChange",(0,g.x)(this.bN,this)));this.i.push(this.Tc.$_s("onlineScreenChange",(0,g.x)(this.NJ,this)))},$qa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.zp("MDX_CONFIG")||b;mqa();D5();B8||(B8=new R6(b?b.loungeApiHost:void 0),J5()&&(B8.g="/api/loungedev"));C8||(C8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",C8,void 0));Wqa();var c=D8();if(!c){var d=new o7(B8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=D8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lqa(a,d,function(m){m?E8()&&X7(E8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){n5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),F8("Initializing: "+g.Kg(b)),G8.push(g.Op("yt-remote-cast2-availability-change",function(){n5("yt-remote-receiver-availability-change")})),G8.push(g.Op("yt-remote-cast2-receiver-selected",function(){H8(null);
n5("yt-remote-auto-connect","cast-selector-receiver")})),G8.push(g.Op("yt-remote-cast2-receiver-resumed",function(){n5("yt-remote-receiver-resumed","cast-selector-receiver")})),G8.push(g.Op("yt-remote-cast2-session-change",Xqa)),G8.push(g.Op("yt-remote-connection-change",function(m){m?X7(E8(),"YouTube TV"):I8()||(X7(null,null),T7())})),a=J8(),b.isAuto&&(a.id+="#dial"),g.vq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),F8(" -- with channel params: "+
g.Kg(a)),Yqa(a),c.start(),E8()||Zqa())},ara=function(){var a=K8();
R7()&&g.ft("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},K8=function(){var a=D8().Tc.$_gos();
var b=L8();b&&M8()&&(w5(a,b)||a.push(b));return lqa(a)},N8=function(){var a=bra();
!a&&R7()&&S7()&&(a={key:"cast-selector-receiver",name:S7()});return a},bra=function(){var a=K8(),b=L8();
b||(b=I8());return g.Ya(a,function(c){return b&&q5(b,c.key)?!0:!1})},L8=function(){var a=E8();
if(!a)return null;var b=D8().Jd();return x5(b,a)},Xqa=function(a){F8("remote.onCastSessionChange_: "+t5(a));
if(a){var b=L8();b&&b.id==a.id?X7(b.id,"YouTube TV"):(b&&O8(),P8(a,1))}else M8()&&O8()},O8=function(){V7()?O7().stopSession():L7("stopSession called before API ready.");
var a=M8();a&&(a.disconnect(1),Q8(null))},R8=function(){var a=M8();
return!!a&&3!=a.getProxyState()},F8=function(a){Y6("remote",a)},D8=function(){if(!S8){var a=g.w("yt.mdx.remote.screenService_");
S8=a?new A8(a):null}return S8},E8=function(){return g.w("yt.mdx.remote.currentScreenId_")},T8=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},U8=function(){return g.w("yt.mdx.remote.connectData_")},H8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},M8=function(){return g.w("yt.mdx.remote.connection_")},Q8=function(a){var b=M8();
H8(null);a||T8("");g.Ia("yt.mdx.remote.connection_",a,void 0);C8&&((0,g.A)(C8,function(c){c(a)}),C8.length=0);
b&&!a?n5("yt-remote-connection-change",!1):!b&&a&&n5("yt-remote-connection-change",!0)},I8=function(){var a=g.gt();
if(!a)return null;var b=D8().Jd();return x5(b,a)},P8=function(a,b){L8()&&L8();
if(V8)W8=a;else{T8(a.id);var c=new p8(B8,a,J8());c.connect(b,U8());c.subscribe("beforeDisconnect",function(d){n5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){M8()&&Q8(null)});
Q8(c)}},Zqa=function(){var a=I8();
a?(F8("Resume connection to: "+t5(a)),P8(a,0)):(H5(),T7(),F8("Skipping connecting because no session screen found."))},Wqa=function(){var a=J8();
if(g.Yb(a)){a=C5();var b=g.ft("yt-remote-session-name")||"",c=g.ft("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},J8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Yqa=function(a){a?(g.et("yt-remote-session-app",a.app),g.et("yt-remote-session-name",a.name)):(y5("yt-remote-session-app"),y5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},X8=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.us(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.iJ);this.l.K(b,"captionschanged",this.gI);this.l.K(b,"captionssettingschanged",this.pA);this.l.K(b,"videoplayerreset",this.wn);this.l.K(b,"mdxautoplaycancel",this.kC);this.O=this.l.K(b,"onVolumeChange",this.By);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.My,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.wn,this);c.subscribe("autoplayUpNext",this.ny,
this);c.subscribe("previousNextChange",this.Jy,this);c.subscribe("nowAutoplaying",this.Fy,this);c.subscribe("autoplayDismissed",this.my,this);this.suggestion=null;this.F=new g.gC(64);this.o=new g.M(this.nA,500,this);g.G(this,this.o);this.A=new g.M(this.oA,1E3,this);g.G(this,this.A);this.I=new Q5(this.HM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.NA,1E3,this);g.G(this,this.P);this.H=new g.zl(this.FF,1E3,this);g.G(this,this.H);this.N=g.Ja;this.pA();this.wn();this.Gk()},Y8=function(a,b){a.u.qd(b,
a.i.getVideoData().lengthSeconds)},$8=function(a){Y8(a,0);
a.o.stop();Z8(a,new g.gC(64))},b9=function(a,b){if(a9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.cA(a.i.getVideoData(1).videoId,c);a.C=h8(a.g).g}},c9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Df,i5(c));Z8(a,new g.gC(1))},d9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{xQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},a9=function(a){return h8(a.g).videoId==a.i.getVideoData(1).videoId},Z8=function(a,b){a.A.stop();
var c=a.F;if(!g.mC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.UJ(a.i,d);a.F=b;e9(a.u,c,b)}},f9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.PP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},h9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.eP()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.PP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);g9(this,g.QJ(a))},g9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.cN("Error on $RECEIVER_NAME",c):g.nC(b)||g.U(b,4)?g.cN("Playing on $RECEIVER_NAME",c):g.cN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},i9=function(a,b){g.xT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},j9=function(a){g.sK.call(this,a);
this.i={key:v5(),name:"This computer"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.mk=new g.gC(64);this.H=0;this.Km=-1;if(!g.Ny(g.X(this.player))){a=this.player;var b=g.$C(a);b&&(b=b.pk())&&(b=new i9(a,b),g.G(this,b));b=new h9(a);g.G(this,b);g.eK(a,b.element,4);this.F=new f9;g.G(this,this.F);g.eK(a,this.F.element,4);this.D=!!I8()}},e9=function(a,b,c){a.mk=c;
a.player.M("presentingplayerstatechange",new g.nD(c,b))},k9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)O8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.zp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.zp("SESSION_INDEX")||g.zp("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),M8()||(V8=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Df,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=i5(c))&&(d.locationInfo=c);c=d}else c=null;F8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(H8(c||null),V7()?O7().setLaunchParams(c||null):L7("setLaunchParams called before ready.")):!c&&R8()&&E8()==b.key?n5("yt-remote-connection-change",!0):(O8(),H8(c||null),c=D8().Jd(),(c=x5(c,b.key))&&P8(c,1))}},bqa=/^https?$/i,cra=["POST",
"PUT"];g.y(g5,g.Sf);g.h=g5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.N?Z4(this.N):Z4(g.yY);this.P=this.N?this.N.getOptions():g.yY.getOptions();this.g.onreadystatechange=(0,g.x)(this.Vv,this);try{W4($4(this,"Opening Xhr")),this.W=!0,this.g.open(b,String(a),!0),this.W=!1}catch(f){W4($4(this,"Error opening Xhr: "+f.message));d5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Zpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Hd(),$pa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(cra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{a5(this),0<this.A&&(this.I=aqa(this.g),W4($4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Wv,this)):this.F=g.Gg(this.Wv,this.A,this)),W4($4(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){W4($4(this,"Send error: "+f.message)),d5(this,f)}};
g.h.Wv=function(){"undefined"!=typeof g.bY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,$4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&($4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),c5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),c5(this,!0));g5.Wa.T.call(this)};
g.h.Vv=function(){this.da()||(this.W||this.C||this.o?f5(this):this.kK())};
g.h.kK=function(){f5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<e5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var e6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},d6={"'":"\\'"},dra={};g.h=m5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Lma)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.yc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var jqa={zN:"atp",LP:"ska",AP:"que",ZO:"mus",KP:"sus",qO:"dsp",HP:"seq"};o5.prototype.gg=function(){var a=new o5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var I5,B5="",rqa=K5("loadCastFramework")||K5("loadCastApplicationFramework"),Kqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(Q5,g.D);g.h=Q5.prototype;g.h.dD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Uc:this.za=g.Gg(this.u,this.Uc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();Q5.Wa.T.call(this)};
g.h.eD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};R5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
R5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=S5.prototype;g.h.ah=null;g.h.xe=!1;g.h.Yi=null;g.h.Ws=null;g.h.Fi=null;g.h.Xh=null;g.h.Xf=null;g.h.Eg=null;g.h.sh=null;g.h.sc=null;g.h.fl=0;g.h.Be=null;g.h.no=null;g.h.pg=null;g.h.Tj=-1;g.h.Pz=!0;g.h.Qg=!1;g.h.Tp=0;g.h.Gn=null;var Z5={},X5={};g.h=S5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.TL=function(a){a=a.target;var b=this.Gn;b&&3==e5(a)?b.Pj():this.WA(a)};
g.h.WA=function(a){try{if(a==this.sc)a:{var b=e5(this.sc),c=this.sc.u,d=this.sc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!h5(this.sc))break a;this.Qg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));i6(this);var e=this.sc.getStatus();this.Tj=e;var f=h5(this.sc);(this.xe=200==e)?(4==b&&a6(this),this.u?(c6(this,b,f),g.Ch&&this.xe&&3==b&&(this.aa.ca(this.i,"tick",this.ML),this.i.start())):$5(this,f),this.xe&&!this.Qg&&(4==b?this.g.tn(this):(this.xe=
!1,W5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pg=3,Y5(13)):(this.pg=0,Y5(14)),a6(this),b6(this))}}catch(k){this.sc&&h5(this.sc)}finally{}};
g.h.ML=function(){var a=e5(this.sc),b=h5(this.sc);this.fl<b.length&&(i6(this),c6(this,a,b),this.xe&&4!=a&&W5(this))};
g.h.kL=function(a){h6((0,g.x)(this.jL,this,a),0)};
g.h.jL=function(a){this.Qg||(i6(this),$5(this,a),W5(this))};
g.h.Ty=function(a){h6((0,g.x)(this.iL,this,a),0)};
g.h.iL=function(a){this.Qg||(a6(this),this.xe=a,this.g.tn(this),this.g.te(4))};
g.h.cancel=function(){this.Qg=!0;a6(this)};
g.h.uL=function(){this.Yi=null;var a=(0,g.H)();0<=a-this.Ws?(2!=this.Xh&&this.g.te(3),a6(this),this.pg=2,Y5(18),b6(this)):g6(this,this.Ws-a)};
g.h.getLastError=function(){return this.pg};g.h=m6.prototype;g.h.Rp=null;g.h.Dd=null;g.h.Hn=!1;g.h.Uv=null;g.h.dm=null;g.h.Fq=null;g.h.Sp=null;g.h.be=null;g.h.Af=-1;g.h.Sj=null;g.h.jj=null;g.h.connect=function(a){this.Sp=a;a=n6(this.g,null,this.Sp);Y5(3);this.Uv=(0,g.H)();var b=this.g.D;null!=b?(this.Sj=b[0],(this.jj=b[1])?(this.be=1,o6(this)):(this.be=2,q6(this))):(Y4(a,"MODE","init"),this.Dd=new S5(this,void 0,void 0,void 0),this.Dd.ah=this.Rp,V5(this.Dd,a,!1,null,!0),this.be=0)};
g.h.lC=function(a){if(a)this.be=2,q6(this);else{Y5(4);var b=this.g;b.Je=b.fg.Af;K6(b,9)}a&&this.te(2)};
g.h.np=function(a){return this.g.np(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.Af=-1};
g.h.Tv=function(){return!1};
g.h.Ny=function(a,b){this.Af=a.Tj;if(0==this.be)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.Af;K6(c,2);return}this.Sj=c[0];this.jj=c[1]}else c=this.g,c.Je=this.Af,K6(c,2);else if(2==this.be)if(this.Hn)Y5(7),this.Fq=(0,g.H)();else if("11111"==b){if(Y5(6),this.Hn=!0,this.dm=(0,g.H)(),c=this.dm-this.Uv,!g.Md||g.pd(10)||500>c)this.Af=200,this.Dd.cancel(),Y5(12),p6(this.g,this,!0)}else Y5(8),this.dm=this.Fq=(0,g.H)(),this.Hn=!1};
g.h.tn=function(){this.Af=this.Dd.Tj;if(this.Dd.xe)0==this.be?this.jj?(this.be=1,o6(this)):(this.be=2,q6(this)):2==this.be&&((!g.Md||g.pd(10)?!this.Hn:200>this.Fq-this.dm)?(Y5(11),p6(this.g,this,!1)):(Y5(12),p6(this.g,this,!0)));else{0==this.be?Y5(9):2==this.be&&Y5(10);var a=this.g;this.Dd.getLastError();a.Je=this.Af;K6(a,2)}};
g.h.Tk=function(){return this.g.Tk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=r6.prototype;g.h.wj=null;g.h.zd=null;g.h.Sb=null;g.h.Qp=null;g.h.gm=null;g.h.ou=null;g.h.rm=null;g.h.Bk=0;g.h.zH=0;g.h.Rc=null;g.h.lg=null;g.h.qf=null;g.h.Vg=null;g.h.fg=null;g.h.ko=null;g.h.ki=-1;g.h.Bw=-1;g.h.Je=-1;g.h.Rh=0;g.h.Jh=0;g.h.Rg=8;var L6=new g.Sf;g.y(s6,g.sf);g.y(t6,g.sf);g.y(u6,g.sf);g.h=r6.prototype;g.h.connect=function(a,b,c,d,e){Y5(0);this.Qp=b;this.wj=c||{};d&&g.Ea(e)&&(this.wj.OSID=d,this.wj.OAID=e);this.A?(h6((0,g.x)(this.Hu,this,a),100),A6(this)):this.Hu(a)};
g.h.Hu=function(a){this.fg=new m6(this);this.fg.Rp=null;this.fg.i=this.u;this.fg.connect(a)};
g.h.Tv=function(){return 0==this.g};
g.h.Sy=function(a){this.lg=null;F6(this,a)};
g.h.Ry=function(){this.qf=null;this.Sb=new S5(this,this.l,"rpc",this.C);this.Sb.ah=null;this.Sb.Tp=0;var a=this.ou.clone();g.Um(a,"RID","rpc");g.Um(a,"SID",this.l);g.Um(a,"CI",this.ko?"0":"1");g.Um(a,"AID",this.ki);w6(this,a);if(!g.Md||g.pd(10))g.Um(a,"TYPE","xmlhttp"),V5(this.Sb,a,!0,this.rm,!1);else{g.Um(a,"TYPE","html");var b=this.Sb,c=!!this.rm;b.Xh=3;b.Xf=X4(a.clone());f6(b,c)}};
g.h.Ny=function(a,b){if(0!=this.g&&(this.Sb==a||this.zd==a))if(this.Je=a.Tj,this.zd==a&&3==this.g)if(7<this.Rg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Sb)if(this.Sb.Fi+3E3<this.zd.Fi)B6(this),this.Sb.cancel(),this.Sb=null;else break a;I6(this);Y5(19)}}else this.Bw=c[1],0<this.Bw-this.ki&&37500>c[2]&&this.ko&&0==this.Jh&&!this.Vg&&(this.Vg=h6((0,g.x)(this.cI,this),6E3));else K6(this,11)}else b!=dra.VN.g&&K6(this,11);else if(this.Sb==a&&
B6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.rm=e[2],e=e[3],null!=e?this.Rg=e:this.Rg=6,this.g=3,this.Rc&&this.Rc.Bu(),this.ou=n6(this,this.Tk()?this.rm:null,this.Qp),G6(this)):"stop"==e[0]&&K6(this,7):3==this.g&&("stop"==e[0]?K6(this,7):"noop"!=e[0]&&this.Rc&&this.Rc.Au(e),this.Jh=0)}}};
g.h.cI=function(){null!=this.Vg&&(this.Vg=null,this.Sb.cancel(),this.Sb=null,I6(this),Y5(20))};
g.h.tn=function(a){if(this.Sb==a){B6(this);this.Sb=null;var b=2}else if(this.zd==a)this.zd=null,b=1;else return;this.Je=a.Tj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.H)()-a.Fi,L6.dispatchEvent(new t6(L6,a.sh?a.sh.length:0,b,this.Rh)),z6(this),this.o.length=0):G6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.zd||this.lg||1==this.g||2<=this.Rh?d=!1:(this.lg=h6((0,g.x)(this.Sy,this,a),H6(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&I6(this))}if(d)switch(c){case 1:K6(this,
5);break;case 4:K6(this,10);break;case 3:K6(this,6);break;case 7:K6(this,12);break;default:K6(this,2)}}};
g.h.DC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.yM=function(a){a?Y5(2):(Y5(1),J6(this,8))};
g.h.np=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Rc&&this.Rc.isActive(this)};
g.h.te=function(a){L6.dispatchEvent(new u6(L6,a))};
g.h.Tk=function(){return!(!g.Md||g.pd(10))};
g.h=M6.prototype;g.h.Bu=function(){};
g.h.Au=function(){};
g.h.zu=function(){};
g.h.bp=function(){};
g.h.xv=function(){return{}};
g.h.isActive=function(){return!0};g.y(N6,g.D);g.h=N6.prototype;g.h.cL=function(){this.Uc=Math.min(3E5,2*this.Uc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.ao(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Uc=5E3};g.y(O6,M6);g.h=O6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.bh(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.qf(this.l),P6(this),g.qf(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new r6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Rc=null);d.Rc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ki):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):Q6(this)&&C6(this.g,c)};
g.h.Bu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)C6(this.g,a[b])}this.M("handlerOpened")};
g.h.zu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.bp=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.xv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Au=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),y6(this.g)):this.M("handlerMessage",new vqa(a[0],a[1]))};
g.h.cM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.zd&&b++;0==b&&this.connect(this.u,this.o)};R6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
R6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
R6.prototype.u=function(a){a(Error("request timed out"))};var Bqa=(0,g.H)(),W6=null,$6=Array(50),Z6=-1,a7=!1;g.y(b7,g.P);b7.prototype.Jd=function(){return this.g};
b7.prototype.contains=function(a){return!!w5(this.g,a)};
b7.prototype.get=function(a){return a?x5(this.g,a):null};
b7.prototype.info=function(a){Y6(this.C,a)};g.t(d7,g.P);g.h=d7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.ZA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Jp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();g.P.prototype.T.call(this)};
g.h.ZA=function(){this.za=NaN;this.g=g.Eq(S6(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.ZM,this),onError:(0,g.x)(this.YM,this),ie:(0,g.x)(this.aN,this)})};
g.h.ZM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new p5(c))};
g.h.YM=function(a){this.g=null;a.status&&404==a.status?this.i>=l9.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=l9[this.i],this.za=g.Hp((0,g.x)(this.ZA,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.aN=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};
var l9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(f7,b7);g.h=f7.prototype;g.h.start=function(){e7(this)&&this.M("screenChange");!g.ft("yt-remote-lounge-token-expiration")&&g7(this);g.Jp(this.i);this.i=g.Hp((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){e7(this);c7(this,a);h7(this,!1);this.M("screenChange");b(a);a.token||g7(this)};
g.h.remove=function(a,b){var c=e7(this);Dqa(this,a)&&(h7(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.eo=function(a,b,c,d){var e=e7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,h7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.T=function(){g.Jp(this.i);f7.Wa.T.call(this)};
g.h.oD=function(a){e7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}h7(this,!b);b&&Y6(this.C,"Missed "+b+" lounge tokens.")};
g.h.nD=function(a){Y6(this.C,"Requesting lounge tokens failed: "+a)};g.t(j7,g.P);g.h=j7.prototype;g.h.start=function(){var a=parseInt(g.ft("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?m7(this):(this.o=(0,g.H)()+3E5,g.et("yt-remote-fast-check-period",this.o),this.Wr())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){i7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!x5(a,d)},this);
l7(this,b)};
g.h.T=function(){g.Jp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.T.call(this)};
g.h.Wr=function(){g.Jp(this.l);this.l=NaN;this.i&&this.i.abort();var a=n7(this);if(j5(a)){var b=S6(this.u,"/pairing/get_screen_availability");this.i=T6(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.GK,this,a),(0,g.x)(this.FK,this))}else l7(this,{}),m7(this)};
g.h.GK=function(a,b){this.i=null;var c=g.Sb(n7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;l7(this,d);m7(this)}else this.Hb("Changing Screen set during request."),this.Wr()};
g.h.FK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;m7(this)};
g.h.Hb=function(a){Y6("OnlineScreenService",a)};g.y(o7,b7);g.h=o7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.eo=function(a,b,c,d){this.l.contains(a)?this.l.eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Y6(this.C,a),d(Error(a)))};
g.h.Jd=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.aB=function(){return(0,g.Yd)(this.Jd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.bB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new d7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(p7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.cN=function(a,b,c,d){g.Eq(S6(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new p5(f.screen||{});if(!k.name||r7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);r7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(p7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ie:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);o7.Wa.T.call(this)};
g.h.wD=function(){s7(this);this.M("screenChange");this.i.update()};
o7.prototype.dispose=o7.prototype.dispose;g.y(u7,g.P);g.h=u7.prototype;g.h.vn=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Md=function(a){this.da()||(a&&v7(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){Y6(this.P,a)};
g.h.dB=function(){return null};
g.h.os=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){v7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.os("");u7.Wa.T.call(this)};g.y(x7,u7);g.h=x7.prototype;g.h.ls=function(a){if(this.g){if(this.g==a)return;v7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Hqa(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.os=g.Ja;g.h.T=function(){this.info("disposeInternal");g.Jp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;x7.Wa.T.call(this)};
g.h.FL=function(a,b){if(!this.da())if(b){var c=l5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":w7(this,c.screenId);break;default:v7(this,"Unknown youtube message: "+d)}}else v7(this,"Unable to parse message.")}else v7(this,"No data in message.")};
g.h.Nv=function(a,b,c,d){q7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(v7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Hp((0,g.x)(this.Nv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dB=function(){return this.g};
g.h.dN=function(a){this.da()||a||(v7(this,"Cast session died."),this.Md())};g.y(y7,u7);g.h=y7.prototype;g.h.ls=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.mi=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Jp(this.A);this.o?this.o.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.T=function(){this.g();this.g=g.Ja;g.Jp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;y7.Wa.T.call(this)};
g.h.gN=function(a){this.da()||a||(v7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Md())};
g.h.hq=function(a){this.H=v5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,A7(this));a(b);z7(this)}else this.C=(0,g.x)(function(){g.Jp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,A7(this));a(c);z7(this)},this),this.A=g.Hp((0,g.x)(function(){this.C()},this),100)};
g.h.SD=function(a,b,c){q7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.vn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.hq(b,c)},this),(0,g.x)(function(d){v7(this,"Failed to get DIAL screen: "+d);
this.hq(b,c)},this))};g.y(B7,u7);B7.prototype.stop=function(){this.Md()};
B7.prototype.ls=g.Ja;B7.prototype.mi=function(){g.Jp(this.g);this.g=NaN;var a=x5(this.F.Jd(),this.i.label);a?this.vn(a):this.Md(Error("No such screen"))};
B7.prototype.T=function(){g.Jp(this.g);this.g=NaN;B7.Wa.T.call(this)};g.y(C7,g.P);g.h=C7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.pK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Py,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.DI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),yqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.cB,this)),this.l=H7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.M("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.lM=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.g.i.friendlyName),G7(this,null)}if(a&&b){if(!this.g){c=x5(this.i.Jd(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=D7(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new B7(this.i,d),!0)}this.g.os(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.mM=function(a){this.da()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Hb("Setting connection data without a session")};
g.h.fN=function(){this.da()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Py,this),(0,g.x)(this.LK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.cB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],U6);g.qf(this.g);C7.Wa.T.call(this)};
g.h.Hb=function(a){Y6("Controller",a)};
g.h.Qy=function(a,b){this.g==a&&(b||G7(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.lK=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new B7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new y7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:G7(this,new x7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.DI=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return E7("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new y7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.SD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.hq,b))};
g.h.Py=function(a){if(!this.da()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new x7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=x5(this.i.Jd(),c.label);d&&q5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new x7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Qy,this,this.g)),this.g.mi(null));this.g.ls(a)}}};
g.h.eN=function(){return this.g?this.g.dB():null};
g.h.LK=function(a){this.da()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.pK=function(a){E7("Receiver availability updated: "+a);if(!this.da()){var b=F7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.M("yt-remote-cast2-availability-change",F7(this))}};
g.h.cB=function(){this.da()||(this.l=H7(this),E7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",F7(this)))};
C7.prototype.setLaunchParams=C7.prototype.mM;C7.prototype.setConnectedScreenStatus=C7.prototype.lM;C7.prototype.stopSession=C7.prototype.fN;C7.prototype.getCastSession=C7.prototype.eN;C7.prototype.requestSession=C7.prototype.requestSession;C7.prototype.init=C7.prototype.init;C7.prototype.dispose=C7.prototype.dispose;var Q7=[];Y7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";Z7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
Y7.prototype.isAdPlaying=function(){return 1081==this.playerState};
Y7.prototype.getDuration=function(){return this.u?this.D+$7(this):this.D};
Y7.prototype.clone=function(){return new Y7(d8(this))};g.t(g8,g.P);g.h=g8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,o8(this,"play")):m8(this,"play"),l8(this,1,b8(h8(this))),this.M("remotePlayerChange")):j8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,o8(this,"pause")):m8(this,"pause"),l8(this,2,b8(h8(this))),this.M("remotePlayerChange")):j8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=h8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,o8(this,"seekTo",{newTime:a}))}else m8(this,"seekTo",{newTime:a});l8(this,3,a);this.M("remotePlayerChange")}else j8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,o8(this,"stopVideo")):m8(this,"stopVideo");var a=h8(this);a.index=-1;a.videoId="";Z7(a);k8(this,a);this.M("remotePlayerChange")}else j8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=h8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){Y6("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){Y6("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);m8(this,"setVolume",e)}c.muted=b;c.volume=a;k8(this,c)}else j8(this,g.Sa(this.setVolume,a,b))};
g.h.cA=function(a,b){if(1==this.g){var c=h8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));m8(this,"setSubtitlesTrack",d);k8(this,c)}else j8(this,g.Sa(this.cA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();m8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=h8(this);d.audioTrackId=c;k8(this,d)}else j8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=h8(this);c=c||0;var m={videoId:a,currentIndex:c};c8(l,a,c);g.Ea(b)&&(a8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));m8(this,"setPlaylist",m);d||k8(this,l)};
g.h.Cn=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);c8(c,a,b);k8(this,c)}m8(this,"previous")}else j8(this,g.Sa(this.Cn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);c8(c,a,b);k8(this,c)}m8(this,"next")}else j8(this,g.Sa(this.nextVideo,a,b))};
g.h.Yu=function(){1==this.g?m8(this,"dismissAutoplay"):j8(this,this.Yu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.T=function(){i8(this);this.o=null;this.u.clear();f8(this,null);g.P.prototype.T.call(this)};
g.h.Zs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.iK=function(a,b){this.M(a,b)};
g.h.iI=function(a){if(!a)this.Ek(null),f8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=h8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Y6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,k8(this,b)}};
g.h.Ek=function(a){Y6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),n8(this),this.M("remotePlayerChange")};
g.h.hI=function(a){a?(n8(this),this.M("remotePlayerChange")):this.Ek(null)};
g.h.Js=function(){m8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.vI=function(){var a=U7();a&&f8(this,a)};
g.h.Hb=function(a){Y6("CP",a)};g.t(p8,g.P);g.h=p8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Ma.listId=c);this.Ma.videoId=d;this.Ma.index=k||0;this.Ma.state=3;a8(this.Ma,m);this.o="UNSUPPORTED";q8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,E5())}else q8("Connecting without params"),this.g.connect({},a,E5());Oqa(this)};
g.h.dispose=function(){this.da()||(this.M("beforeDispose"),r8(this,3));g.P.prototype.dispose.call(this)};
g.h.T=function(){s8(this);u8(this);t8(this);g.Jp(this.C);this.C=NaN;g.Jp(this.D);this.D=NaN;this.l=null;g.Nr(this.P);this.P.length=0;this.g.dispose();g.P.prototype.T.call(this);this.o=this.A=this.i=this.Ma=this.g=null};
g.h.hD=function(){this.Nh(2)};
g.h.mI=function(){q8("Channel opened");this.I&&(this.I=!1,t8(this),this.H=g.Hp((0,g.x)(function(){q8("Timing out waiting for a screen.");this.Nh(1)},this),15E3));
pqa(wqa(this.g),this.N)};
g.h.jI=function(){q8("Channel closed");isNaN(this.u)?H5(!0):H5();this.dispose()};
g.h.kI=function(a){H5();isNaN(this.Gj())?(q8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,q8("Channel error: "+a+" with reconnection in "+this.Gj()+" ms"),r8(this,2))};
g.h.lI=function(a){a.params?q8("Received: action="+a.action+", params="+g.Kg(a.params)):q8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=l5(a.params.devices);this.i=(0,g.B)(a,function(c){return new o5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
x8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
x8(this,!1);break;case "remoteConnected":var b=new o5(l5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||eqa(this.i,b);
break;case "remoteDisconnected":b=new o5(l5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":y8(this,a);break;case "nowPlaying":Rqa(this,a);break;case "onStateChange":z8(this,a);break;case "onAdStateChange":Sqa(this,a);break;case "onVolumeChanged":Tqa(this,a);break;case "onSubtitlesTrackChanged":Qqa(this,a);break;case "nowAutoplaying":Uqa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.M("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":Vqa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:q8("Unrecognized action: "+a.action)}};
g.h.ZL=function(){if(this.l){var a=this.l;this.l=null;this.Ma.videoId!=a&&v8(this,"getNowPlaying")}};
g.h.XC=function(){var a=3;this.da()||(a=0,isNaN(this.Gj())?Q6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Nh=function(a){q8("Disconnecting with "+a);s8(this);this.M("beforeDisconnect",a);1==a&&H5();P6(this.g,a);this.dispose()};
g.h.WC=function(){var a=this.Ma;this.l&&(a=this.Ma.clone(),c8(a,this.l,a.index));return d8(a)};
g.h.nM=function(a){var b=new Y7(a);b.videoId&&b.videoId!=this.Ma.videoId&&(this.l=b.videoId,g.Jp(this.C),this.C=g.Hp((0,g.x)(this.ZL,this),5E3));var c=[];this.Ma.listId==b.listId&&this.Ma.videoId==b.videoId&&this.Ma.index==b.index||c.push("remoteQueueChange");this.Ma.playerState==b.playerState&&this.Ma.volume==b.volume&&this.Ma.muted==b.muted&&b8(this.Ma)==b8(b)&&g.Kg(this.Ma.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Ma.reset(a);(0,g.A)(c,function(d){this.M(d)},this)};
g.h.Kv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Gj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.PC=function(){return this.o||"UNSUPPORTED"};
g.h.QC=function(){return this.A||""};
g.h.XM=function(){if(!isNaN(this.Gj())){var a=this.g.i;g.bo(a.g);a.start()}};
g.h.gM=function(a,b){v8(this,a,b);w8(this)};
p8.prototype.subscribe=p8.prototype.subscribe;p8.prototype.unsubscribeByKey=p8.prototype.Kf;p8.prototype.getProxyState=p8.prototype.XC;p8.prototype.disconnect=p8.prototype.Nh;p8.prototype.getPlayerContextData=p8.prototype.WC;p8.prototype.setPlayerContextData=p8.prototype.nM;p8.prototype.getOtherConnectedRemoteId=p8.prototype.Kv;p8.prototype.getReconnectTimeout=p8.prototype.Gj;p8.prototype.getAutoplayMode=p8.prototype.PC;p8.prototype.getAutoplayVideoId=p8.prototype.QC;p8.prototype.reconnect=p8.prototype.XM;
p8.prototype.sendMessage=p8.prototype.gM;g.t(A8,b7);g.h=A8.prototype;g.h.Jd=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.add=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Tc.$_ubk(this.i[a]);this.i.length=0;this.Tc=null;b7.prototype.T.call(this)};
g.h.bN=function(){this.M("screenChange")};
g.h.NJ=function(){this.M("onlineScreenChange")};
o7.prototype.$_st=o7.prototype.start;o7.prototype.$_gspc=o7.prototype.cN;o7.prototype.$_gsppc=o7.prototype.bB;o7.prototype.$_c=o7.prototype.contains;o7.prototype.$_g=o7.prototype.get;o7.prototype.$_a=o7.prototype.add;o7.prototype.$_un=o7.prototype.eo;o7.prototype.$_r=o7.prototype.remove;o7.prototype.$_gs=o7.prototype.Jd;o7.prototype.$_gos=o7.prototype.aB;o7.prototype.$_s=o7.prototype.subscribe;o7.prototype.$_ubk=o7.prototype.Kf;var W8=null,V8=!1,B8=null,C8=null,S8=null,G8=[];g.t(X8,g.D);g.h=X8.prototype;
g.h.T=function(){g.D.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.My,this);this.g.unsubscribe("remotePlayerChange",this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.wn,this);this.g.unsubscribe("autoplayUpNext",this.ny,this);this.g.unsubscribe("previousNextChange",this.Jy,this);this.g.unsubscribe("nowAutoplaying",this.Fy,this);this.g.unsubscribe("autoplayDismissed",this.my,this);this.g=this.u=null};
g.h.kx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(a9(this)){if(!h8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==h8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Pj(c[0],c[1]);break;case "control_subtitles_set_track":b9(this,c[0]);break;case "control_set_audio_track":c=c[0],a9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();c9(this,0==c?void 0:c);break;case "control_seek":c9(this,c[0]);break;case "control_subtitles_set_track":b9(this,c[0]);break;case "control_set_audio_track":c=c[0],a9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.gI=function(a){this.I.dD(a)};
g.h.HM=function(a){this.kx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.pA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||b9(this,a)};
g.h.By=function(a){if(a9(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=h8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.iJ=function(){g.Yb(this.C)||d9(this,this.C);this.D=!1};
g.h.My=function(a,b){this.A.stop();2==b&&this.oA()};
g.h.Gk=function(){if(a9(this)){this.o.stop();var a=h8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Km=1;break;case 1082:case 1083:this.u.Km=0;break;default:this.u.Km=-1}switch(a.playerState){case 1081:case 1:Z8(this,new g.gC(8));this.nA();break;case 1085:case 3:Z8(this,new g.gC(9));break;case 1083:case 0:Z8(this,new g.gC(2));this.H.stop();Y8(this,this.i.getVideoData().lengthSeconds);break;case 1084:Z8(this,new g.gC(4));break;case 2:Z8(this,new g.gC(4));Y8(this,b8(a));
break;case -1:Z8(this,new g.gC(64));break;case -1E3:Z8(this,new g.gC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=h8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,d9(this,a));a=h8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.NA()}else $8(this)};
g.h.Jy=function(){this.i.M("mdxpreviousnextchange")};
g.h.wn=function(){a9(this)||$8(this)};
g.h.kC=function(){this.g.Yu()};
g.h.ny=function(a){a&&(a=g.Eq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.nL,this)}))&&(this.N=(0,g.x)(a.abort,a))};
g.h.nL=function(a,b){var c=new g.UA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.Fy=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.my=function(){this.i.M("mdxautoplaycanceled")};
g.h.FF=function(a,b){-1==h8(this.g).playerState?c9(this,a):b&&this.g.seekTo(a)};
g.h.NA=function(){if(a9(this)){var a=h8(this.g);this.l.La(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.By)}};
g.h.nA=function(){this.o.stop();if(!this.g.da()){var a=h8(this.g);1==a.playerState&&Z8(this,new g.gC(8));Y8(this,b8(a));this.o.start()}};
g.h.oA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(f9,g.W);f9.prototype.o=function(){n5("mdx-privacy-popup-cancel");this.l.hide()};
f9.prototype.A=function(){n5("mdx-privacy-popup-confirm");this.l.hide()};g.t(h9,g.W);h9.prototype.u=function(a){g9(this,a.state)};g.t(i9,g.xT);i9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.yT(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
i9.prototype.A=function(a){return a.key};
i9.prototype.re=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
i9.prototype.Ic=function(a){g.xT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(j9,g.sK);g.h=j9.prototype;
g.h.create=function(){$qa(g.Ey(g.X(this.player)));this.o.push(g.Op("yt-remote-before-disconnect",this.dI,this));this.o.push(g.Op("yt-remote-connection-change",this.qK,this));this.o.push(g.Op("yt-remote-receiver-availability-change",this.Ky,this));this.o.push(g.Op("yt-remote-auto-connect",this.oK,this));this.o.push(g.Op("yt-remote-receiver-resumed",this.nK,this));this.o.push(g.Op("mdx-privacy-popup-confirm",this.PL,this));this.o.push(g.Op("mdx-privacy-popup-cancel",this.OL,this));this.Ky()};
g.h.load=function(){this.player.cancelPlayback();g.sK.prototype.load.call(this);this.u=new X8(this,this.player,this.g);var a=(a=U8())?a.currentTime:0;var b=R8()?new g8(M8(),void 0):null;0==a&&b&&(a=b8(h8(b)));0!=a&&this.qd(a);e9(this,this.mk,this.mk);g.xX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.sK.prototype.unload.call(this);g.xX(this.player.app,5)};
g.h.T=function(){g.Pp(this.o);g.sK.prototype.T.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.kx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Km};
g.h.ZC=function(){return this.loaded?this.u.suggestion:null};
g.h.Ke=function(){return this.g?h8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?h8(this.g).hasNext:!1};
g.h.qd=function(a,b){this.H=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=h8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ac():!a.isAdPlaying()&&this.player.ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+$7(a):a.l,isAtLiveHead:1>=(a.u?a.i+$7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+$7(a):a.i,seekableStart:0<a.o?a.o+
$7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Cn=function(){this.g&&this.g.Cn()};
g.h.dI=function(a){1==a&&(this.C=this.g?h8(this.g):null)};
g.h.qK=function(){var a=R8()?new g8(M8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,b8(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ky=function(){this.A=[this.i].concat(ara());var a=N8()||this.i;k9(this,a);this.player.la("onMdxReceiversChange")};
g.h.oK=function(){var a=N8();k9(this,a)};
g.h.nK=function(){this.l=N8()};
g.h.PL=function(){this.D=!0;V8=!1;W8&&P8(W8,1);W8=null};
g.h.OL=function(){this.D=!1;k9(this,this.i);this.l=this.i;V8=!1;W8=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?W7():k9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&W7(),!0):!1}};
g.h.Js=function(){this.g.Js()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.OU.remote=j9;})(_yt_player);
